version: '3.9'

services:
  db:
    container_name: postgresdb
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "host=postgresdb user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:  
  pgdata: {}